apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: slack-notify-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "30"
  labels:
    codefresh.io/cert: slack-job 
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
